# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Melanoma' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Melanoma
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'MelanomaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MelanomaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
